apiVersion: v1
kind: Secret
metadata:
  name: admin-pass-secret
  namespace: default
data:
  password: "YXNkZg==" # password: "asdf"
---
apiVersion: nycae.io/v1alpha1
kind: Account
metadata:
  name: player-admin
spec:
  username: "admin"
  email: "admin@server.com"
  gmLevel: 3
  expansion: 2
  passwordSecretRef:
    name: admin-pass-secret
    namespace: default
    key: password