apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-authserver
  labels:
    app.kubernetes.io/name: authserver
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.authServer.service.port }}
    targetPort: realmlist
    protocol: TCP
    name: realmlist
  selector:
    app.kubernetes.io/name: authserver
    app.kubernetes.io/instance: {{ .Release.Name }}