apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-authserver
  labels:
    app.kubernetes.io/name: authserver
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.authServer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: authserver
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authserver
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: sql-files
        emptyDir: { }
      initContainers:
      - name: db-import
        image: "acore/ac-wotlk-db-import:master"
        imagePullPolicy: {{ .Values.authServer.image.pullPolicy }}
        env:
        - name: AC_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-root-password
        - name: AC_LOGIN_DATABASE_INFO
          value: "{{ .Release.Name }}-mysql;3306;root;$(AC_ROOT_PASS);acore_auth"
        - name: AC_CHARACTER_DATABASE_INFO
          value: "{{ .Release.Name }}-mysql;3306;root;$(AC_ROOT_PASS);acore_characters"
        - name: AC_WORLD_DATABASE_INFO
          value: "{{ .Release.Name }}-mysql;3306;root;$(AC_ROOT_PASS);acore_world"
      containers:
      - name: authserver
        image: "{{ .Values.authServer.image.repository }}:{{ .Values.authServer.image.tag }}"
        imagePullPolicy: {{ .Values.authServer.image.pullPolicy }}
        env:
        - name: AC_MYSQL_ALLOW_OLD_VERSION
          value: "1"
        - name: AC_UPDATES_ENABLE_DATABASES
          value: "1"
        - name: AC_UPDATES_AUTOMIGRATE
          value: "1"
        - name: AC_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-root-password
        - name: AC_LOGIN_DATABASE_INFO
          value: "{{ .Release.Name }}-mysql;3306;root;$(AC_ROOT_PASS);acore_auth"
        - name: AC_CHARACTER_DATABASE_INFO
          value: "{{ .Release.Name }}-mysql;3306;root;$(AC_ROOT_PASS);acore_characters"
        - name: AC_WORLD_DATABASE_INFO
          value: "{{ .Release.Name }}-mysql;3306;root;$(AC_ROOT_PASS);acore_world"
        ports:
        - containerPort: 3724
          protocol: TCP
          hostPort: 3724
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi